###########################################################
#      Detailed information on how to edit the config     #
#                     can be found here:                  #
#  http://dev.bukkit.org/server-mods/death-and-rebirth/   #
#                                                         #
#                         Spout                           #
#                                                         #
# No need to edit this if you aren't using Spout.         #
# Remember to put a backslash in front of a colon in URLs.#
# Colors use RGB values, so 1;0;0 would be red.           #
#                                                         #
#               Additional information                    #
#                Don't edit this lines:                   #
#            SPOUT_ENABLED and CITIZENS_ENABLED           #
#                                                         #
###########################################################
BLOCK_GHOST_INTERACTION: false
FLY: false
FLY_SPEED: 0.75
GHOST_CHAT: true
GHOST_NAME: Ghost of %player%
INVISIBILITY: true
LIGHTNING_DEATH: true
LIGHTNING_REBIRTH: true

DROPPING: false
PVP_DROP: true

HEALTH: 10
PERCENT: 15
ECONOMY: 0

MCMMO: false
XP: 0
SKILLS:
    ACROBATICS: false
    ARCHERY: false
    AXES: false
    EXCAVATION: false
    HERBALISM: false
    MINING: false
    REPAIR: false
    SWORDS: false
    TAMING: false
    UNARMED: false
    WOODCUTTING: false

NEED_ITEM: false
ITEM_ID: 288
AMOUNT: 1
DISTANCE: 10
TIME: 10

CORPSE_SPAWNING: false

GRAVE_SIGNS: true
SHRINE_NOTE: true
SHRINE_RADIUS: 3
SHRINE_ONLY: false
VERSION_CHECK: true
VOID_DEATH: true
ADMIN_PERMS: false
SHRINE_PROTECTION: true

GHOST_SOUND_EFFECTS: true
DEATH_SOUND: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/sounds/death.wav
REB_SOUND: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/sounds/res.wav
RES_SOUND: 

GHOST_SKIN: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/skins/ghost1.png
GHOST_TEXTPACK: http://your_texturepack.com

CHANGE_COLORS: true
GHOST_SKY: 0.8;0;0
GHOST_FOG: 0.8;0;0
GHOST_CLOUDS: 0;0;0

SPOUT_ENABLED: false
CITIZENS_ENABLED: false