###########################################################
#      Detailed information on how to edit the config     #
#                     can be found here:                  #
#  http://dev.bukkit.org/server-mods/death-and-rebirth/   #
#                                                         #
#                         Spout                           #
#                                                         #
# No need to edit this if you aren't using Spout.         #
# Remember to put a backslash in front of a colon in URLs.#
# Colors use RGB values, so 1;0;0 would be red.           #
#                                                         #
#               Additional information                    #
#                Don't edit this lines:                   #
#            SPOUT_ENABLED and CITIZENS_ENABLED           #
#                                                         #
###########################################################
BLOCK_GHOST_INTERACTION: false
FLY: false
FLY_SPEED: 0.75
GHOST_CHAT: true
GHOST_NAME: 'Ghost of %player%'
INVISIBILITY: true
LIGHTNING_DEATH: true
LIGHTNING_REBIRTH: true
CROSS_WORLD_GHOST: true
KEEP_INVENTORY_CROSS_WORLD: true
GHOST_WORLD_CHANGE: true
COMPASS: true
DISABLED_COMMANDS:
- /command1
- /command2

DROPPING: false
PVP_DROP: true

HEALTH: 30
PERCENT: 15
ECONOMY: 0
GRAVEROBBERY: 0.0
ROBBERY_ITEMS:
- 256
- 269
- 273

MCMMO: false
XP: 0
SKILLS:
    ACROBATICS: false
    ARCHERY: false
    AXES: false
    EXCAVATION: false
    HERBALISM: false
    MINING: false
    REPAIR: false
    SWORDS: false
    TAMING: false
    UNARMED: false
    WOODCUTTING: false

CORPSE_SPAWNING: false

GRAVE_SIGNS: true
WATER_GRAVE: false
SHRINE_NOTE: true
SHRINE_RADIUS: 3
SHRINE_ONLY: false

VERSION_CHECK: true
VOID_DEATH: true
ADMIN_PERMS: false
PERMISSIONS: true
SHRINE_PROTECTION: true

GHOST_SOUND_EFFECTS: true
DEATH_SOUND: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/sounds/death.wav
REB_SOUND: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/sounds/res.wav
RES_SOUND: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/sounds/res.wav

GHOST_SKIN: http://dl.dropbox.com/u/12769915/minecraft/plugins/DAR/skins/ghost1.png
GHOST_TEXTPACK: http://your_texturepack.com

CHANGE_COLORS: true
GHOST_SKY: 0.8;0;0
GHOST_FOG: 0.8;0;0
GHOST_CLOUDS: 0;0;0

GRAVE_TEXT: R.I.P

HARDCORE: false
TIMER: 0
OTHERS_RESURRECT: true
OTHERS_PAYMENT: 0
OTHERS_HEALTH: 50
NEED_ITEM: false
RES_ITEM: 322
AMOUNT: 1
DISTANCE: 3
RESURRECT_TIME: 10
ONLY_DAY: false

SPOUT_ENABLED: false
CITIZENS_ENABLED: false
MOBARENA_ENABLED: false
HEROES_ENABLED: false